project:
  type: website
  output-dir: docs

website:
  title: "A trip down memory lane"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - costa-rica-2021.qmd
      - peru-2022.qmd

format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
    toc: true
    page-layout: full
    
 
