---
title: "Questions-Answers"
author: "Veronique Letourneau"
date: 2023-05-26
format: html
---

Link to GitHub Repo: https://github.com/veronique-let/choyoa-2_mysite

Webpage URL: https://veronique-let.github.io/choyoa-2_mysite/

### Problem 1.

3.  I highlighted some of my favorite pictures taken from two of my trips, with a home page introducing myself and the about page describing my travels and motivation to share.
    I went with my 2020 Costa Rica trip and Peru 2023.

### My Experience.

8-10 sentences summarizing your experience, addressing (for example): What was hard about this? What was easy? What was new to you? What was familiar to you?

I absolutely loved doing this project! It was hard at first to figure out exactly how to link the repo to a webpage, but once I had gotten that figured out, the ball was rolling! Everything about this assignment was new to me but in such an exciting way! I am honestly hoping to get to learn more about GitHub pages, this was an interesting thing to do. A major factor for my enthusiasm in doing this project was being able to look back at my travel photos and share with you! I am very proud of how it came out and have received very nice feedback from people around me finding it quite impressive! So fun:)
